version: "3.9"  # optional since v1.27.0
services:
  bind9:
    container_name: practica1_bind9
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 5300:53/udp
      - 5300:53/tcp
    volumes:
      - /home/asir2a/Escritorio/SRI/DNS/config:/etc/bind
      - /home/asir2a/Escritorio/SRI/DNS/zonas:/var/lib/bind
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.254
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks:
      - bind9_subnet
    stdin_open: true
    tty: true
    dns:
      - 10.1.0.254
networks:
  bind9_subnet:
    external: true
